services:
  db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-database-server
    environment:
      SA_PASSWORD: "SenhaBancoDeDadosTeste.123"
      ACCEPT_EULA: "Y"

    ports:
       - "1434:1433"
    volumes:
      - sql-data:/var/opt/mssql

  controlefinanceiro.api:
    image: ${DOCKER_REGISTRY-}controlefinanceiroapi
    build:
      context: .
      dockerfile: ControleFinanceiro.API/Dockerfile
    depends_on:
      - db

  controlefinanceiro.view:
    container_name: react_frontend_view
    build:
      context: ./controlefinanceiro.view
      dockerfile: Dockerfile
    depends_on:
      - controlefinanceiro.api
    ports:
      - "3000:3000"
    volumes:
      - ./controlefinanceiro.view:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - WATCHPACK_POLLING=true
      - VITE_HOST=0.0.0.0

volumes:
  sql-data:
    driver: local
